### ISSUE TITLE
[bug] not: command not found

### ISSUE THREAD

**Issue by Freed-Wu** [Anty0/updaurpkg#1]
In <https://github.com/Anty0/updaurpkg/blob/main/updaurpkg#L94> and <https://github.com/Anty0/updaurpkg/blob/main/updaurpkg#L65>

**Comment by Anty0** [comment]
Well, I guess `not` is not in POSIX standard :D
Wasn't problem on my system. I'll have to find out what implemented `not` on my system 🤔

Anyway I'll change them to `!`. That seems like good idea.

Thanks for the report. :)

**Comment by Anty0** [comment]
Bit unexpected :thinking:
```
$ pacman -Qo /usr/sbin/not
/usr/bin/not is owned by llvm
```

**Comment by Anty0** [comment]
Anyway, it should be fixed now.
